import Head from "next/head";
import Image from "next/image";
import * as S from "../layout/Home";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>SUNG JE KIM / Velog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Wrapper>
        <S.Container>
          <p>Hi.</p>
          <p>VELOG</p>
          <p>SUNG</p>
          <p>JE</p>
          <p>KIM</p>
        </S.Container>
      </S.Wrapper>
    </>
  );
}
